export default function Head() {
    return (
        <>
            <title>Alex Esaki</title>
            <meta content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by alex georgy esaki" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}